package portfolio.ian.com.leaguematchhistory.Activities.ActivityDataHandling;

import android.content.res.Resources;
import android.graphics.drawable.Drawable;

import java.util.ArrayList;

import portfolio.ian.com.leaguematchhistory.R;

/**
 * Created by Ian on 16/06/2016.
 */
public class Rune {
    public Long runeId, rank;
    public String name, description;
    public static ArrayList<Rune> runes = new ArrayList<>();

    public Rune(Long runeId, Long rank, String name, String description) {
        this.runeId = runeId;
        this.rank = rank;
        this.name = name;
        this.description = description;
    }

    public static Drawable runeIdToImage(Resources resource, long runeID) {
        String tempRuneId = String.valueOf(runeID);
        switch (tempRuneId) {
            case "5001":
                return resource.getDrawable(R.drawable.lesser_mark_of_attack_damage);
            case "5002":
                return resource.getDrawable(R.drawable.lesser_mark_of_scaling_attack_damage);
            case "5003":
                return resource.getDrawable(R.drawable.lesser_mark_of_attack_speed);
            case "5005":
                return resource.getDrawable(R.drawable.lesser_mark_of_critical_damage);
            case "5007":
                return resource.getDrawable(R.drawable.lesser_mark_of_critical_chance);
            case "5009":
                return resource.getDrawable(R.drawable.lesser_mark_of_armor_penetration);
            case "5011":
                return resource.getDrawable(R.drawable.lesser_mark_of_health);
            case "5012":
                return resource.getDrawable(R.drawable.lesser_mark_of_scaling_health);
            case "5013":
                return resource.getDrawable(R.drawable.lesser_mark_of_armor);
            case "5015":
                return resource.getDrawable(R.drawable.lesser_mark_of_magic_resist);
            case "5016":
                return resource.getDrawable(R.drawable.lesser_mark_of_scaling_magic_resist);
            case "5021":
                return resource.getDrawable(R.drawable.lesser_mark_of_cooldown_reduction);
            case "5023":
                return resource.getDrawable(R.drawable.lesser_mark_of_ability_power);
            case "5024":
                return resource.getDrawable(R.drawable.lesser_mark_of_scaling_ability_power);
            case "5025":
                return resource.getDrawable(R.drawable.lesser_mark_of_mana);
            case "5026":
                return resource.getDrawable(R.drawable.lesser_mark_of_scaling_mana);
            case "5027":
                return resource.getDrawable(R.drawable.lesser_mark_of_mana_regeneration);
            case "5029":
                return resource.getDrawable(R.drawable.lesser_mark_of_magic_penetration);
            case "5031":
                return resource.getDrawable(R.drawable.lesser_glyph_of_attack_damage);
            case "5032":
                return resource.getDrawable(R.drawable.lesser_glyph_of_scaling_attack_damage);
            case "5033":
                return resource.getDrawable(R.drawable.lesser_glyph_of_attack_speed);
            case "5035":
                return resource.getDrawable(R.drawable.lesser_glyph_of_critical_damage);
            case "5037":
                return resource.getDrawable(R.drawable.lesser_glyph_of_critical_chance);
            case "5041":
                return resource.getDrawable(R.drawable.lesser_glyph_of_health);
            case "5042":
                return resource.getDrawable(R.drawable.lesser_glyph_of_scaling_health);
            case "5043":
                return resource.getDrawable(R.drawable.lesser_glyph_of_armor);
            case "5045":
                return resource.getDrawable(R.drawable.lesser_glyph_of_magic_resist);
            case "5046":
                return resource.getDrawable(R.drawable.lesser_glyph_of_scaling_magic_resist);
            case "5047":
                return resource.getDrawable(R.drawable.lesser_glyph_of_health_regeneration);
            case "5051":
                return resource.getDrawable(R.drawable.lesser_glyph_of_cooldown_reduction);
            case "5052":
                return resource.getDrawable(R.drawable.lesser_glyph_of_scaling_cooldown_reduction);
            case "5053":
                return resource.getDrawable(R.drawable.lesser_glyph_of_ability_power);
            case "5054":
                return resource.getDrawable(R.drawable.lesser_glyph_of_scaling_ability_power);
            case "5055":
                return resource.getDrawable(R.drawable.lesser_glyph_of_mana);
            case "5056":
                return resource.getDrawable(R.drawable.lesser_glyph_of_scaling_mana);
            case "5057":
                return resource.getDrawable(R.drawable.lesser_glyph_of_mana_regeneration);
            case "5058":
                return resource.getDrawable(R.drawable.lesser_glyph_of_scaling_mana_regeneration);
            case "5059":
                return resource.getDrawable(R.drawable.lesser_glyph_of_magic_penetration);
            case "5061":
                return resource.getDrawable(R.drawable.lesser_seal_of_attack_damage);
            case "5062":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_attack_damage);
            case "5063":
                return resource.getDrawable(R.drawable.lesser_seal_of_attack_speed);
            case "5065":
                return resource.getDrawable(R.drawable.lesser_seal_of_critical_damage);
            case "5067":
                return resource.getDrawable(R.drawable.lesser_seal_of_critical_chance);
            case "5071":
                return resource.getDrawable(R.drawable.lesser_seal_of_health);
            case "5072":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_health);
            case "5073":
                return resource.getDrawable(R.drawable.lesser_seal_of_armor);
            case "5074":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_armor);
            case "5075":
                return resource.getDrawable(R.drawable.lesser_seal_of_magic_resist);
            case "5076":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_magic_resist);
            case "5077":
                return resource.getDrawable(R.drawable.lesser_seal_of_health_regeneration);
            case "5078":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_health_regeneration);
            case "5081":
                return resource.getDrawable(R.drawable.lesser_seal_of_cooldown_reduction);
            case "5083":
                return resource.getDrawable(R.drawable.lesser_seal_of_ability_power);
            case "5084":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_ability_power);
            case "5085":
                return resource.getDrawable(R.drawable.lesser_seal_of_mana);
            case "5086":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_mana);
            case "5087":
                return resource.getDrawable(R.drawable.lesser_seal_of_mana_regeneration);
            case "5088":
                return resource.getDrawable(R.drawable.lesser_seal_of_scaling_mana_regeneration);
            case "5091":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_attack_damage);
            case "5092":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_attack_damage);
            case "5093":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_attack_speed);
            case "5095":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_critical_damage);
            case "5097":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_critical_chance);
            case "5099":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_armor_penetration);
            case "5101":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_health);
            case "5102":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_health);
            case "5103":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_armor);
            case "5104":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_armor);
            case "5105":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_magic_resist);
            case "5106":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_magic_resist);
            case "5107":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_health_regeneration);
            case "5108":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_health_regeneration);
            case "5111":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_cooldown_reduction);
            case "5112":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_cooldown_reduction);
            case "5113":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_ability_power);
            case "5114":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_ability_power);
            case "5115":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_mana);
            case "5116":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_mana);
            case "5117":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_mana_regeneration);
            case "5118":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_scaling_mana_regeneration);
            case "5119":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_magic_penetration);
            case "5121":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_movement_speed);
            case "5123":
                return resource.getDrawable(R.drawable.mark_of_attack_damage);
            case "5124":
                return resource.getDrawable(R.drawable.mark_of_scaling_attack_damage);
            case "5125":
                return resource.getDrawable(R.drawable.mark_of_attack_speed);
            case "5127":
                return resource.getDrawable(R.drawable.mark_of_critical_damage);
            case "5129":
                return resource.getDrawable(R.drawable.mark_of_critical_chance);
            case "5131":
                return resource.getDrawable(R.drawable.mark_of_armor_penetration);
            case "5133":
                return resource.getDrawable(R.drawable.mark_of_health);
            case "5134":
                return resource.getDrawable(R.drawable.mark_of_scaling_health);
            case "5135":
                return resource.getDrawable(R.drawable.mark_of_armor);
            case "5137":
                return resource.getDrawable(R.drawable.mark_of_magic_resist);
            case "5138":
                return resource.getDrawable(R.drawable.mark_of_scaling_magic_resist);
            case "5143":
                return resource.getDrawable(R.drawable.mark_of_cooldown_reduction);
            case "5145":
                return resource.getDrawable(R.drawable.mark_of_ability_power);
            case "5146":
                return resource.getDrawable(R.drawable.mark_of_scaling_ability_power);
            case "5147":
                return resource.getDrawable(R.drawable.mark_of_mana);
            case "5148":
                return resource.getDrawable(R.drawable.mark_of_scaling_mana);
            case "5149":
                return resource.getDrawable(R.drawable.mark_of_mana_regeneration);
            case "5151":
                return resource.getDrawable(R.drawable.mark_of_magic_penetration);
            case "5153":
                return resource.getDrawable(R.drawable.glyph_of_attack_damage);
            case "5154":
                return resource.getDrawable(R.drawable.glyph_of_scaling_attack_damage);
            case "5155":
                return resource.getDrawable(R.drawable.glyph_of_attack_speed);
            case "5157":
                return resource.getDrawable(R.drawable.glyph_of_critical_damage);
            case "5159":
                return resource.getDrawable(R.drawable.glyph_of_critical_chance);
            case "5163":
                return resource.getDrawable(R.drawable.glyph_of_health);
            case "5164":
                return resource.getDrawable(R.drawable.glyph_of_scaling_health);
            case "5165":
                return resource.getDrawable(R.drawable.glyph_of_armor);
            case "5167":
                return resource.getDrawable(R.drawable.glyph_of_magic_resist);
            case "5168":
                return resource.getDrawable(R.drawable.glyph_of_scaling_magic_resist);
            case "5169":
                return resource.getDrawable(R.drawable.glyph_of_health_regeneration);
            case "5173":
                return resource.getDrawable(R.drawable.glyph_of_cooldown_reduction);
            case "5174":
                return resource.getDrawable(R.drawable.glyph_of_scaling_cooldown_reduction);
            case "5175":
                return resource.getDrawable(R.drawable.glyph_of_ability_power);
            case "5176":
                return resource.getDrawable(R.drawable.glyph_of_scaling_ability_power);
            case "5177":
                return resource.getDrawable(R.drawable.glyph_of_mana);
            case "5178":
                return resource.getDrawable(R.drawable.glyph_of_scaling_mana);
            case "5179":
                return resource.getDrawable(R.drawable.glyph_of_mana_regeneration);
            case "5180":
                return resource.getDrawable(R.drawable.glyph_of_scaling_mana_regeneration);
            case "5181":
                return resource.getDrawable(R.drawable.glyph_of_magic_penetration);
            case "5183":
                return resource.getDrawable(R.drawable.seal_of_attack_damage);
            case "5184":
                return resource.getDrawable(R.drawable.seal_of_scaling_attack_damage);
            case "5185":
                return resource.getDrawable(R.drawable.seal_of_attack_speed);
            case "5187":
                return resource.getDrawable(R.drawable.seal_of_critical_damage);
            case "5189":
                return resource.getDrawable(R.drawable.seal_of_critical_chance);
            case "5193":
                return resource.getDrawable(R.drawable.seal_of_health);
            case "5194":
                return resource.getDrawable(R.drawable.seal_of_scaling_health);
            case "5195":
                return resource.getDrawable(R.drawable.seal_of_armor);
            case "5196":
                return resource.getDrawable(R.drawable.seal_of_scaling_armor);
            case "5197":
                return resource.getDrawable(R.drawable.seal_of_magic_resist);
            case "5198":
                return resource.getDrawable(R.drawable.seal_of_scaling_magic_resist);
            case "5199":
                return resource.getDrawable(R.drawable.seal_of_health_regeneration);
            case "5200":
                return resource.getDrawable(R.drawable.seal_of_scaling_health_regeneration);
            case "5203":
                return resource.getDrawable(R.drawable.seal_of_cooldown_reduction);
            case "5205":
                return resource.getDrawable(R.drawable.seal_of_ability_power);
            case "5206":
                return resource.getDrawable(R.drawable.seal_of_scaling_ability_power);
            case "5207":
                return resource.getDrawable(R.drawable.seal_of_mana);
            case "5208":
                return resource.getDrawable(R.drawable.seal_of_scaling_mana);
            case "5209":
                return resource.getDrawable(R.drawable.seal_of_mana_regeneration);
            case "5210":
                return resource.getDrawable(R.drawable.seal_of_scaling_mana_regeneration);
            case "5213":
                return resource.getDrawable(R.drawable.quintessence_of_attack_damage);
            case "5214":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_attack_damage);
            case "5215":
                return resource.getDrawable(R.drawable.quintessence_of_attack_speed);
            case "5217":
                return resource.getDrawable(R.drawable.quintessence_of_critical_damage);
            case "5219":
                return resource.getDrawable(R.drawable.quintessence_of_critical_chance);
            case "5221":
                return resource.getDrawable(R.drawable.quintessence_of_armor_penetration);
            case "5223":
                return resource.getDrawable(R.drawable.quintessence_of_health);
            case "5224":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_health);
            case "5225":
                return resource.getDrawable(R.drawable.quintessence_of_armor);
            case "5226":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_armor);
            case "5227":
                return resource.getDrawable(R.drawable.quintessence_of_magic_resist);
            case "5228":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_magic_resist);
            case "5229":
                return resource.getDrawable(R.drawable.quintessence_of_health_regeneration);
            case "5230":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_health_regeneration);
            case "5233":
                return resource.getDrawable(R.drawable.quintessence_of_cooldown_reduction);
            case "5234":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_cooldown_reduction);
            case "5235":
                return resource.getDrawable(R.drawable.quintessence_of_ability_power);
            case "5236":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_ability_power);
            case "5237":
                return resource.getDrawable(R.drawable.quintessence_of_mana);
            case "5238":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_mana);
            case "5239":
                return resource.getDrawable(R.drawable.quintessence_of_mana_regeneration);
            case "5240":
                return resource.getDrawable(R.drawable.quintessence_of_scaling_mana_regeneration);
            case "5241":
                return resource.getDrawable(R.drawable.quintessence_of_magic_penetration);
            case "5243":
                return resource.getDrawable(R.drawable.quintessence_of_movement_speed);
            case "5245":
                return resource.getDrawable(R.drawable.greater_mark_of_attack_damage);
            case "5246":
                return resource.getDrawable(R.drawable.greater_mark_of_scaling_attack_damage);
            case "5247":
                return resource.getDrawable(R.drawable.greater_mark_of_attack_speed);
            case "5249":
                return resource.getDrawable(R.drawable.greater_mark_of_critical_damage);
            case "5251":
                return resource.getDrawable(R.drawable.greater_mark_of_critical_chance);
            case "5253":
                return resource.getDrawable(R.drawable.greater_mark_of_armor_penetration);
            case "5255":
                return resource.getDrawable(R.drawable.greater_mark_of_health);
            case "5256":
                return resource.getDrawable(R.drawable.greater_mark_of_scaling_health);
            case "5257":
                return resource.getDrawable(R.drawable.greater_mark_of_armor);
            case "5259":
                return resource.getDrawable(R.drawable.greater_mark_of_magic_resist);
            case "5260":
                return resource.getDrawable(R.drawable.greater_mark_of_scaling_magic_resist);
            case "5265":
                return resource.getDrawable(R.drawable.greater_mark_of_cooldown_reduction);
            case "5267":
                return resource.getDrawable(R.drawable.greater_mark_of_ability_power);
            case "5268":
                return resource.getDrawable(R.drawable.greater_mark_of_scaling_ability_power);
            case "5269":
                return resource.getDrawable(R.drawable.greater_mark_of_mana);
            case "5270":
                return resource.getDrawable(R.drawable.greater_mark_of_scaling_mana);
            case "5271":
                return resource.getDrawable(R.drawable.greater_mark_of_mana_regeneration);
            case "5273":
                return resource.getDrawable(R.drawable.greater_mark_of_magic_penetration);
            case "5275":
                return resource.getDrawable(R.drawable.greater_glyph_of_attack_damage);
            case "5276":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_attack_damage);
            case "5277":
                return resource.getDrawable(R.drawable.greater_glyph_of_attack_speed);
            case "5279":
                return resource.getDrawable(R.drawable.greater_glyph_of_critical_damage);
            case "5281":
                return resource.getDrawable(R.drawable.greater_glyph_of_critical_chance);
            case "5285":
                return resource.getDrawable(R.drawable.greater_glyph_of_health);
            case "5286":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_health);
            case "5287":
                return resource.getDrawable(R.drawable.greater_glyph_of_armor);
            case "5289":
                return resource.getDrawable(R.drawable.greater_glyph_of_magic_resist);
            case "5290":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_magic_resist);
            case "5291":
                return resource.getDrawable(R.drawable.greater_glyph_of_health_regeneration);
            case "5295":
                return resource.getDrawable(R.drawable.greater_glyph_of_cooldown_reduction);
            case "5296":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_cooldown_reduction);
            case "5297":
                return resource.getDrawable(R.drawable.greater_glyph_of_ability_power);
            case "5298":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_ability_power);
            case "5299":
                return resource.getDrawable(R.drawable.greater_glyph_of_mana);
            case "5300":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_mana);
            case "5301":
                return resource.getDrawable(R.drawable.greater_glyph_of_mana_regeneration);
            case "5302":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_mana_regeneration);
            case "5303":
                return resource.getDrawable(R.drawable.greater_glyph_of_magic_penetration);
            case "5305":
                return resource.getDrawable(R.drawable.greater_seal_of_attack_damage);
            case "5306":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_attack_damage);
            case "5307":
                return resource.getDrawable(R.drawable.greater_seal_of_attack_speed);
            case "5309":
                return resource.getDrawable(R.drawable.greater_seal_of_critical_damage);
            case "5311":
                return resource.getDrawable(R.drawable.greater_seal_of_critical_chance);
            case "5315":
                return resource.getDrawable(R.drawable.greater_seal_of_health);
            case "5316":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_health);
            case "5317":
                return resource.getDrawable(R.drawable.greater_seal_of_armor);
            case "5318":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_armor);
            case "5319":
                return resource.getDrawable(R.drawable.greater_seal_of_magic_resist);
            case "5320":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_magic_resist);
            case "5321":
                return resource.getDrawable(R.drawable.greater_seal_of_health_regeneration);
            case "5322":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_health_regeneration);
            case "5325":
                return resource.getDrawable(R.drawable.greater_seal_of_cooldown_reduction);
            case "5327":
                return resource.getDrawable(R.drawable.greater_seal_of_ability_power);
            case "5328":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_ability_power);
            case "5329":
                return resource.getDrawable(R.drawable.greater_seal_of_mana);
            case "5330":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_mana);
            case "5331":
                return resource.getDrawable(R.drawable.greater_seal_of_mana_regeneration);
            case "5332":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_mana_regeneration);
            case "5335":
                return resource.getDrawable(R.drawable.greater_quintessence_of_attack_damage);
            case "5336":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_attack_damage);
            case "5337":
                return resource.getDrawable(R.drawable.greater_quintessence_of_attack_speed);
            case "5339":
                return resource.getDrawable(R.drawable.greater_quintessence_of_critical_damage);
            case "5341":
                return resource.getDrawable(R.drawable.greater_quintessence_of_critical_chance);
            case "5343":
                return resource.getDrawable(R.drawable.greater_quintessence_of_armor_penetration);
            case "5345":
                return resource.getDrawable(R.drawable.greater_quintessence_of_health);
            case "5346":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_health);
            case "5347":
                return resource.getDrawable(R.drawable.greater_quintessence_of_armor);
            case "5348":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_armor);
            case "5349":
                return resource.getDrawable(R.drawable.greater_quintessence_of_magic_resist);
            case "5350":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_magic_resist);
            case "5351":
                return resource.getDrawable(R.drawable.greater_quintessence_of_health_regeneration);
            case "5352":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_health_regeneration);
            case "5355":
                return resource.getDrawable(R.drawable.greater_quintessence_of_cooldown_reduction);
            case "5356":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_cooldown_reduction);
            case "5357":
                return resource.getDrawable(R.drawable.greater_quintessence_of_ability_power);
            case "5358":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_ability_power);
            case "5359":
                return resource.getDrawable(R.drawable.greater_quintessence_of_mana);
            case "5360":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_mana);
            case "5361":
                return resource.getDrawable(R.drawable.greater_quintessence_of_mana_regeneration);
            case "5362":
                return resource.getDrawable(R.drawable.greater_quintessence_of_scaling_mana_regeneration);
            case "5363":
                return resource.getDrawable(R.drawable.greater_quintessence_of_magic_penetration);
            case "5365":
                return resource.getDrawable(R.drawable.greater_quintessence_of_movement_speed);
            case "5366":
                return resource.getDrawable(R.drawable.greater_quintessence_of_revival);
            case "5367":
                return resource.getDrawable(R.drawable.greater_quintessence_of_gold);
            case "5368":
                return resource.getDrawable(R.drawable.greater_quintessence_of_experience);
            case "5369":
                return resource.getDrawable(R.drawable.greater_seal_of_energy_regeneration);
            case "5370":
                return resource.getDrawable(R.drawable.greater_seal_of_scaling_energy_regeneration);
            case "5371":
                return resource.getDrawable(R.drawable.greater_glyph_of_energy);
            case "5372":
                return resource.getDrawable(R.drawable.greater_glyph_of_scaling_energy);
            case "5373":
                return resource.getDrawable(R.drawable.greater_quintessence_of_energy_regeneration);
            case "5374":
                return resource.getDrawable(R.drawable.greater_quintessence_of_energy);
            case "5400":
                return resource.getDrawable(R.drawable.lesser_mark_of_hybrid_penetration);
            case "5401":
                return resource.getDrawable(R.drawable.mark_of_hybrid_penetration);
            case "5402":
                return resource.getDrawable(R.drawable.greater_mark_of_hybrid_penetration);
            case "5403":
                return resource.getDrawable(R.drawable.greater_seal_of_gold);
            case "5404":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_percent_health);
            case "5405":
                return resource.getDrawable(R.drawable.quintessence_of_percent_health);
            case "5406":
                return resource.getDrawable(R.drawable.greater_quintessence_of_percent_health);
            case "5407":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_spell_vamp);
            case "5408":
                return resource.getDrawable(R.drawable.quintessence_of_spell_vamp);
            case "5409":
                return resource.getDrawable(R.drawable.greater_quintessence_of_spell_vamp);
            case "5410":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_life_steal);
            case "5411":
                return resource.getDrawable(R.drawable.quintessence_of_life_steal);
            case "5412":
                return resource.getDrawable(R.drawable.greater_quintessence_of_life_steal);
            case "5413":
                return resource.getDrawable(R.drawable.lesser_seal_of_percent_health);
            case "5414":
                return resource.getDrawable(R.drawable.seal_of_percent_health);
            case "5415":
                return resource.getDrawable(R.drawable.greater_seal_of_percent_health);
            case "5416":
                return resource.getDrawable(R.drawable.lesser_quintessence_of_hybrid_penetration);
            case "5417":
                return resource.getDrawable(R.drawable.quintessence_of_hybrid_penetration);
            case "5418":
                return resource.getDrawable(R.drawable.greater_quintessence_of_hybrid_penetration);
            case "8001":
                return resource.getDrawable(R.drawable.mark_of_the_crippling_candy_cane);
            case "8002":
                return resource.getDrawable(R.drawable.lesser_mark_of_the_yuletide_tannenbaum_);
            case "8003":
                return resource.getDrawable(R.drawable.glyph_of_the_special_stocking);
            case "8005":
                return resource.getDrawable(R.drawable.lesser_glyph_of_the_gracious_gift);
            case "8006":
                return resource.getDrawable(R.drawable.lesser_seal_of_the_stout_snowman);
            case "8007":
                return resource.getDrawable(R.drawable.lesser_mark_of_alpine_attack_speed);
            case "8008":
                return resource.getDrawable(R.drawable.mark_of_the_combatant);
            case "8009":
                return resource.getDrawable(R.drawable.lesser_seal_of_the_medalist);
            case "8011":
                return resource.getDrawable(R.drawable.lesser_glyph_of_the_challenger);
            case "8012":
                return resource.getDrawable(R.drawable.glyph_of_the_soaring_slalom);
            case "8013":
                return resource.getDrawable(R.drawable.quintessence_of_the_headless_horseman);
            case "8014":
                return resource.getDrawable(R.drawable.quintessence_of_the_piercing_screech);
            case "8015":
                return resource.getDrawable(R.drawable.quintessence_of_bountiful_treats);
            case "8016":
                return resource.getDrawable(R.drawable.quintessence_of_the_speedy_specter);
            case "8017":
                return resource.getDrawable(R.drawable.quintessence_of_the_witches_brew);
            case "8019":
                return resource.getDrawable(R.drawable.greater_quintessence_of_the_piercing_present);
            case "8020":
                return resource.getDrawable(R.drawable.greater_quintessence_of_the_deadly_wreath);
            case "8021":
                return resource.getDrawable(R.drawable.greater_quintessence_of_frosty_health);
            case "8022":
                return resource.getDrawable(R.drawable.greater_quintessence_of_sugar_rush);
            case "8035":
                return resource.getDrawable(R.drawable.greater_quintessence_of_studio_rumble);
        }
        return null;
    }
}
